function [diff_term,static_term,diff_term_norm,static_term_norm] = ...
    timeIntBleachFn(s,tauGrid,kSqGrid,k_p,T)

A = s.diffusion.*kSqGrid;

% diffusing autocorrelation factor
diff_term = (-1).*A.^(-1).*exp(1).^((-1).*A.*(1+tauGrid)+(-1).*s.K.*(1+tauGrid)+(-1).*k_p.*( ...
    T+tauGrid)).*((-1)+exp(1).^k_p).^(-1).*((-1).*exp(1).^(k_p.*T)+exp(1).^( ...
    k_p.*tauGrid)).*(A+s.K).^(-1).*(A+k_p).^(-1).*(A+s.K+k_p).^(-1).*((-1).*A.*(( ...
    -1)+exp(1).^(A+s.K)).*((-1)+exp(1).^(A+s.K+k_p)).*(A+k_p).*((-1)+s.r)+exp( ...
    1).^(s.K+s.K.*tauGrid).*((-1)+exp(1).^A).*((-1)+exp(1).^(A+k_p)).*(A+s.K).*(A+ ...
    s.K+k_p).*s.r).*(T+(-1).*tauGrid).^(-1);
%
% static autocorrelation term
static_term = (1/2).*exp(1).^((-1).*s.K.*(1+tauGrid)+(-1).*k_p.*(2.*T+tauGrid)).*((-1).*exp(1) ...
    .^(k_p.*T)+exp(1).^(k_p.*tauGrid)).*s.K.^(-1).*k_p.^(-2).*(s.K+k_p).^(-1).*(exp( ...
    1).^(k_p.*T).*k_p.^2.*((-1)+s.r)+(-1).*exp(1).^(s.K+k_p.*T).*k_p.^2.*((-1) ...
    +s.r)+exp(1).^(k_p+k_p.*T).*k_p.^2.*((-1)+s.r)+(-2).*exp(1).^(s.K+k_p+k_p.*T) ...
    .*k_p.^2.*((-1)+s.r)+exp(1).^(2.*s.K+k_p+k_p.*T).*k_p.^2.*((-1)+s.r)+(-1).* ...
    exp(1).^(s.K+k_p.*(2+T)).*k_p.^2.*((-1)+s.r)+exp(1).^(2.*s.K+k_p.*(2+T)).* ...
    k_p.^2.*((-1)+s.r)+(-2).*exp(1).^((s.K+k_p).*(1+tauGrid)).*s.K.*(s.K+k_p).*s.r+(-2).* ...
    exp(1).^(s.K+k_p+k_p.*T+s.K.*tauGrid).*s.K.*(s.K+k_p).*s.r+exp(1).^(s.K+(s.K+k_p).*tauGrid).*s.K.* ...
    (s.K+k_p).*s.r+exp(1).^(s.K+2.*k_p+(s.K+k_p).*tauGrid).*s.K.*(s.K+k_p).*s.r+(-1).*exp(1) ...
    .^(s.K+2.*k_p+k_p.*T+s.K.*tauGrid).*s.K.*((-1)+k_p).*(s.K+k_p).*s.r+exp(1).^(s.K+k_p.*T+ ...
    s.K.*tauGrid).*s.K.*(1+k_p).*(s.K+k_p).*s.r).*(T+(-1).*tauGrid).^(-1).*((-1)+coth(k_p));
%
% diffusing autocorrelation term (norm)
diff_term_norm = 2.*A.^(-1).*exp(1).^((-1).*A+(-1).*s.K+(-1).*k_p.*T).*((-1)+exp(1) ...
    .^k_p).^(-1).*((-1)+exp(1).^(k_p.*T)).*(A+s.K).^(-1).*k_p.^(-1).*(A+k_p) ...
    .^(-1).*(A+s.K+k_p).^(-1).*(A.^3.*exp(1).^(A+s.K).*((-1)+exp(1).^k_p)+( ...
    -1).*exp(1).^s.K.*((-1)+exp(1).^A).*s.K.*k_p.*(s.K+k_p).*s.r+A.^2.*(k_p+(-1) ...
    .*k_p.*s.r+exp(1).^s.K.*k_p.*s.r+exp(1).^(A+s.K+k_p).*(s.K+k_p+s.K.*s.r)+(-1).*exp( ...
    1).^(A+s.K).*(s.K+2.*k_p+s.K.*s.r))+A.*((-1).*k_p.^2.*((-1)+s.r)+exp(1).^s.K.* ...
    k_p.*(2.*s.K+k_p).*s.r+exp(1).^(A+s.K+k_p).*s.K.*(k_p+s.K.*s.r)+(-1).*exp(1).^(A+ ...
    s.K).*(k_p.*(s.K+k_p)+s.K.*(s.K+2.*k_p).*s.r))).*T.^(-1);
%
% static autocorrelation term (norm)
static_term_norm = (-1/2).*exp(1).^((-1).*s.K+(-2).*k_p.*T).*((-1)+exp(1).^(k_p.*T)).* ...
    s.K.^(-1).*k_p.^(-2).*(s.K+k_p).^(-1).*(exp(1).^s.K.*((-1)+exp(1).^k_p) ...
    .^2.*s.K.*(s.K+k_p).*s.r+exp(1).^(k_p.*T).*(2.*(1+exp(1).^k_p).*k_p.^2.*(( ...
    -1)+s.r)+exp(1).^s.K.*(exp(1).^(2.*k_p).*s.K.*(k_p.*((-2)+s.r)+(-1).*s.K.*s.r)+( ...
    s.K+k_p).*(3.*s.K.*s.r+2.*k_p.*(1+((-1)+s.K).*s.r))+2.*exp(1).^k_p.*((-1).* ...
    s.K.^2.*s.r+k_p.*(k_p+((-1)+s.K).*(s.K+k_p).*s.r))))).*T.^(-1).*((-1)+coth(k_p));
%