#!/bin/bash

Q_TYPE="condor" # input either "condor" or "torque"

########### INPUT VARIABLES ###################

# These variables don't need to be updated in either analysisInput.txt, or submitMatlabJob

RUNTAG=""																			# default: $(date +"%Y-%m-%d-%Hh%Mm%Ss")
RUNCLASS=""																			# organizational subdirectory
CODECLASS="SOFI-Project" 															# project name
CODEPATH="/media/3TB-GPU-Drive/simon.sehayek/Simon/Code" 							# folder containing all codes (recursive)
BASEDIR="/media/3TB-GPU-Drive/simon.sehayek/Simon/runs/${CODECLASS}/data-analysis" 	# folder for storing the runs

# path to stored data file
LOADPATH="/media/3TB-GPU-Drive/simon.sehayek/Simon/runs/SOFI-Project/data-analysis/Saved Sessions/Feb 24/ROI_X_250_336_Y_31_125_TOI_2550_4000.sv.mat"	
				
###############################################


#rm QSub*
#rm Execute*
#rm program_output.txt
	
# unique job names (temp directory)
NEWDIR="${BASEDIR}/queued-jobs/"
UUID=$(uuidgen)
NEWDIR="${NEWDIR}${UUID}"
#

mkdir -p "${NEWDIR}"

cd "${BASEDIR}"

sed -i '/runTag/c\'\'"${RUNTAG}\' |"' runTag' analysisInput.txt
sed -i '/runClass/c\'\'"${RUNCLASS}\' |"' runClass' analysisInput.txt
sed -i '/runDir/c\'\'"${NEWDIR}\' |"' runDir' analysisInput.txt
sed -i '/baseDir/c\'\'"${BASEDIR}\' |"' baseDir' analysisInput.txt
sed -i '/loadPath/c\'\'"${LOADPATH}\' |"' loadPath' analysisInput.txt

sed -i '/NEWDIR=/c\NEWDIR='\""${NEWDIR}"\"'' submitMatlabJob
sed -i '/CODEPATH=/c\CODEPATH='\""${CODEPATH}"\"'' submitMatlabJob
sed -i '/CODECLASS=/c\CODECLASS='\""${CODECLASS}"\"'' submitMatlabJob
sed -i '/RUNTAG=/c\RUNTAG='\""${RUNTAG}"\"'' submitMatlabJob

cd "${CODEPATH}/GeneralUtilities"
#ln -s ${CODEPATH}/GeneralUtilities/getAnalysisInput.m ${NEWDIR}
cp getAnalysisInput.m{,.tmp}
mv getAnalysisInput.m "${NEWDIR}"
cp getAnalysisInput{.m.tmp,.m}
rm getAnalysisInput.m.tmp

cd "${BASEDIR}"

cp analysisInput.txt{,.mv}
mv analysisInput.txt.mv "${NEWDIR}"

cp submitMatlabJob{,.mv}
mv submitMatlabJob.mv "$NEWDIR"

if [[ "$Q_TYPE" == "condor" ]]
then 
	cp condor_script{,.mv}
	mv condor_script.mv "$NEWDIR"		
fi

cd "${NEWDIR}"

### SUBMIT JOB TO QUEUE

if [[ "$Q_TYPE" == "torque" ]]
then	
	qsub -V \
		-o outputfile \
		-e errorfile \
		-l h_rt=24:00:00 \
		-cwd \
		-N "simon_job" \
		-m e \
		-M "${USER}@gmail.com" \
		"submitMatlabJob.mv"
		
	rm submitMatlabJob.mv
else 
	condor_submit condor_script.mv
fi
