#!/bin/bash

## pmem 15700m usually used
########### INPUT VARIABLES ###################

# These variables will be updated by preSubScript

CODEPATH="/media/3TB-GPU-Drive/simon.sehayek/Simon/Code/sofi-project-priv"
NEWDIR="/media/3TB-GPU-Drive/simon.sehayek/Simon/runs/SOFI-Project/data-analysis/queued-jobs/cf6c4179-eff2-463f-9bc9-4321e69530a7"
#CODECLASS="SOFI-Project"
RUNTAG=""

###############################################
cd "${NEWDIR}"

MSCRIPT="${CODEPATH}/cluster-compilers/data-analysis/dataClusterCode.m"

DATETAG=$(date +"%Y-%m-%d-%Hh%Mm%Ss")
matlab -nodisplay < "$MSCRIPT" > "${NEWDIR}/${DATETAG}.out" 2> "${NEWDIR}/${DATETAG}.err"

if [[ -d "${NEWDIR}" ]] 			# only execute if new directory exists
then 
	cd "${NEWDIR}"			
	rm getAnalysisInput.m		

	chmod -R -f 740 "${NEWDIR}" 	# change permissions
fi

rm condor_script.mv submitMatlabJob.mv