#!/bin/bash

########### INPUT VARIABLES ###################

# These variables will be updated by preSubScript

CODEPATH="/media/3TB-GPU-Drive/simon.sehayek/research-projects/code"
TMPDIR="/media/3TB-GPU-Drive/simon.sehayek/research-projects/kics-reboot/queued-jobs/2020-10-15-19h26m03s/"

DATETAG="2020-10-15-19h26m03s"
###############################################

cd "${TMPDIR}"

MSCRIPT="${CODEPATH}/kics-project/simulation-compilers/cluster/kICSFitSimulations.m"

matlab -nodisplay < "$MSCRIPT" > "${TMPDIR}/matlab_out" 2> "${TMPDIR}/matlab_err"

rm -d "${TMPDIR}"