#!/bin/bash

########### INPUT VARIABLES ###################

# These variables don't need to be updated in either analysisInput.txt, or submitMatlabJob

RUNNAME="tau1-5--kSqMax-3"						# default: $(date +"%Y-%m-%d-%Hh%Mm%Ss")
RUNCLASS="no-aggregates-test" 						# organizational subdirectory
CODECLASS="SOFI-Project" 						# project name
CODEPATH="/media/3TB-GPU-Drive/simon.sehayek/Simon/Code/" 		# folder containing all codes (recursive)
BASEDIR="/media/3TB-GPU-Drive/simon.sehayek/Simon/runs/${CODECLASS}" 	# folder for storing the runs

CREATESIM=1	# Create simulations logical
FITSIM=1 	# Compare theory to simulations logical
LOADREP=1 	# Simulation repetition number to load (only relevant if FITSIM=1 & CREATESIM=0)
###############################################

#rm QSub*
#rm Execute*
#rm program_output.txt

if [[ -z "${RUNNAME}" ]] # set RUNNAME to default if variable is empty
then
	RUNNAME=$(date +"%Y-%m-%d-%Hh%Mm%Ss")
fi

if [[ ${CREATESIM} -eq 1 ]] # $LOADREP is not relevant if creating another simulation,
			    # in this case $LOADREP is set to empty MATLAB array
then 
	LOADREP="[]"
fi

NEWDIR="${BASEDIR}/queued-jobs/job"

N=1;
while [[ -d "${NEWDIR}_${N}" ]]
do
	N=$[$N+1]
done
NEWDIR="${NEWDIR}_${N}"

mkdir -p "${NEWDIR}"

cd "${BASEDIR}"

sed -i '/runName/c\'\'"${RUNNAME}\' |"' runName' analysisInput.txt
sed -i '/runClass/c\'\'"${RUNCLASS}\' |"' runClass' analysisInput.txt
sed -i '/runDir/c\'\'"${NEWDIR}\' |"' runDir' analysisInput.txt
sed -i '/baseDir/c\'\'"${BASEDIR}\' |"' baseDir' analysisInput.txt

sed -i '/createSim/c\'"${CREATESIM} |"' createSim' analysisInput.txt
sed -i '/fitSim/c\'"${FITSIM} |"' fitSim' analysisInput.txt
sed -i '/loadRep/c\'"${LOADREP} |"' loadRep' analysisInput.txt

sed -i '/NEWDIR=/c\NEWDIR='\""${NEWDIR}"\"'' submitMatlabJob
sed -i '/CODEPATH=/c\CODEPATH='\""${CODEPATH}"\"'' submitMatlabJob
sed -i '/CODECLASS=/c\CODECLASS='\""${CODECLASS}"\"'' submitMatlabJob
sed -i '/RUNNAME=/c\RUNNAME='\""${RUNNAME}"\"'' submitMatlabJob

cd "${CODEPATH}GeneralUtilities"
#ln -s ${CODEPATH}GeneralUtilities/getAnalysisInput.m ${NEWDIR}
cp getAnalysisInput.m{,.tmp}
mv getAnalysisInput.m "${NEWDIR}"
cp getAnalysisInput{.m.tmp,.m}
rm getAnalysisInput.m.tmp

cd "${BASEDIR}"

cp analysisInput.txt{,.mv}
mv analysisInput.txt.mv "${NEWDIR}"

cp submitMatlabJob{,.mv}
mv submitMatlabJob.mv "$NEWDIR"

cd "${NEWDIR}"

### SUBMIT JOB TO QUEUE

qsub -V \
	-o outputfile \
	-e errorfile \
	-l h_rt=24:00:00 \
	-cwd \
	-N "simon_job" \
	-m e \
	-M "$USER@gmail.com" \
	"submitMatlabJob.mv"

rm submitMatlabJob.mv