#!/bin/bash

########### INPUT VARIABLES ###################

# These variables don't need to be updated in either analysisInput.txt, or submitMatlabJob

RUN=$(date +"%Y-%m-%d-%Hh%Mm%Ss")
CODECLASS="SOFI-Project"
CODEPATH="/media/3TB-GPU-Drive/simon.sehayek/Simon/Code/"
BASEDIR="/media/3TB-GPU-Drive/simon.sehayek/Simon/runs/${CODECLASS}" 

CREATESIM=1 # Create simulations logical
FITSIM=1 # Compare theory to simulations logical
###############################################

rm QSub*
rm Execute*
rm program_output.txt

NEWDIR="${BASEDIR}/${RUN}/"
mkdir -p "${NEWDIR}"

cd "${BASEDIR}"

sed -i '/runDir/c\'\'"${NEWDIR}\' |"' runDir' analysisInput.txt
sed -i '/createSim/c\'"${CREATESIM} |"' createSim' analysisInput.txt
sed -i '/fitSim/c\'"${FITSIM} |"' fitSim' analysisInput.txt

sed -i '/NEWDIR=/c\NEWDIR='\""${NEWDIR}"\"'' submitMatlabJob
sed -i '/CODEPATH=/c\CODEPATH='\""${CODEPATH}"\"'' submitMatlabJob
sed -i '/CODECLASS=/c\CODECLASS='\""${CODECLASS}"\"'' submitMatlabJob
sed -i '/RUN=/c\RUN='\""${RUN}"\"'' submitMatlabJob

cd "${CODEPATH}GeneralUtilities"
#ln -s ${CODEPATH}GeneralUtilities/getAnalysisInput.m ${NEWDIR}
cp getAnalysisInput.m{,.tmp}
mv getAnalysisInput.m "${NEWDIR}"
cp getAnalysisInput{.m.tmp,.m}
rm getAnalysisInput.m.tmp

cd "${BASEDIR}"

cp analysisInput.txt{,.mv}
mv analysisInput.txt.mv "${NEWDIR}"

cp submitMatlabJob{,.mv}
mv submitMatlabJob.mv "$NEWDIR"

cd "${NEWDIR}"

### SUBMIT JOB TO QUEUE

qsub -V \
	-o outputfile \
	-e errorfile \
	-l h_rt=24:00:00 \
	-cwd \
	-N "simon_job" \
	-m e \
	-M "$USER@gmail.com" \
	"submitMatlabJob.mv"

rm submitMatlabJob.mv