function [imm_autocorr,imm_autocorr_norm] = kICSSlideWinImmBleachFn(s,tauGrid)

%% numerator

% intensity autocorrelation
autocorr_ii = exp(1).^((-1).*s.K+(-1).*(s.K+s.kp).*tauGrid).*(exp(1).^s.kp).^((-1).*s.T).*((-1)+ ...
    exp(1).^s.kp).^(-1).*((exp(1).^s.kp).^s.T+(-1).*(exp(1).^s.kp).^tauGrid).*s.K.^( ...
    -1).*s.kp.^(-1).*(s.K+s.kp).^(-1).*s.r.*(((-1)+exp(1).^s.K).*((-1)+exp(1).^( ...
    s.K+s.kp)).*s.kp.*((-1)+s.r)+(-1).*exp(1).^(s.K+s.K.*tauGrid).*((-1)+exp(1).^s.kp).* ...
    s.K.*(s.K+s.kp).*s.r).*((-1).*s.T+tauGrid).^(-1);
%

% window autocorrelation
autocorr_ww = ((-1)+exp(1).^s.kp).^(-2).*s.K.^(-1).*s.kp.^(-2).*(s.K+s.kp).^(-1).*s.r.*s.Ts.^( ...
    -2).*(exp(1).^((-1).*s.K.*(1+tauGrid)+(-1).*s.kp.*((-1)+s.T+2.*s.Ts+tauGrid)).*((-1)+ ...
    exp(1).^(s.kp.*s.Ts)).*(exp(1).^(s.kp.*(s.T+s.Ts))+(-1).*exp(1).^(s.kp.*(s.Ts+tauGrid) ...
    )).*s.kp.*((1+(-1).*exp(1).^s.K).*((-1)+exp(1).^(s.K+s.kp)).*s.kp.*((-1)+s.r)+ ...
    exp(1).^(s.K+s.K.*tauGrid).*((-1)+exp(1).^s.kp).*s.K.*(s.K+s.kp).*s.r)+(-2).*exp(1).^( ...
    (-1).*s.K+(-1).*s.kp.*(s.Ts+tauGrid)).*(exp(1).^s.kp).^((-1).*s.T).*(exp(1).^(s.kp.* ...
    (1+s.Ts))+(-1).*exp(1).^(s.kp.*(1+tauGrid))).*((exp(1).^s.kp).^s.T+(-1).*(exp(1) ...
    .^s.kp).^tauGrid).*(s.kp.^2.*((-1)+s.r)+(-1).*exp(1).^(s.K+s.kp).*s.K.*(s.kp+s.K.*s.r)+ ...
    exp(1).^s.K.*(s.K+s.kp).*(s.kp+s.K.*s.r+((-1)+s.K).*s.kp.*s.r))+exp(1).^((-1).*s.K.*( ...
    1+s.Ts+tauGrid)+(-1).*s.kp.*((-1)+s.T+s.Ts+tauGrid)).*(exp(1).^s.kp).^((-1).*s.Ts).*(exp( ...
    1).^(s.kp.*s.T)+(-1).*exp(1).^(s.kp.*tauGrid)).*s.kp.*(exp(1).^((s.K+s.kp).*(1+s.Ts)) ...
    .*s.kp.*((-1)+s.r)+exp(1).^s.K.*(exp(1).^s.kp).^s.Ts.*s.kp.*((-1)+s.r)+(-1).* ...
    exp(1).^(s.K+s.kp).*(exp(1).^s.kp).^s.Ts.*s.kp.*((-1)+s.r)+(-1).*exp(1).^(s.K+( ...
    s.K+s.kp).*s.Ts).*(exp(1).^s.kp).^s.Ts.*s.kp.*((-1)+s.r)+exp(1).^((s.K+s.kp).*s.Ts).*( ...
    (-1)+(exp(1).^s.kp).^s.Ts).*s.kp.*((-1)+s.r)+exp(1).^((s.K+s.kp).*(1+s.Ts)+s.K.*tauGrid) ...
    .*s.K.*(s.K+s.kp).*s.r+exp(1).^(s.kp.*s.Ts+s.K.*(1+s.Ts+tauGrid)).*((-1)+(exp(1).^s.kp) ...
    .^s.Ts).*s.K.*(s.K+s.kp).*s.r+exp(1).^(s.K.*(1+s.Ts+tauGrid)).*(exp(1).^s.kp).^s.Ts.*s.K.*( ...
    s.K+s.kp).*s.r.*s.Ts+(-1).*exp(1).^(s.kp+s.K.*(1+s.Ts+tauGrid)).*(exp(1).^s.kp).^s.Ts.*s.K.* ...
    (s.K+s.kp).*s.r.*(1+s.Ts))+exp(1).^((-1).*s.K.*(1+tauGrid)+(-1).*s.kp.*((-1)+s.T+tauGrid)).* ...
    (exp(1).^s.kp).^((-1).*s.Ts).*(exp(1).^(s.kp.*s.T)+(-1).*exp(1).^(s.kp.*tauGrid)) ...
    .*s.kp.*(exp(1).^(s.K+s.kp).*s.kp.*((-1)+s.r)+(-1).*exp(1).^s.K.*(exp(1).^s.kp) ...
    .^s.Ts.*s.kp.*((-1)+s.r)+exp(1).^(2.*s.K+s.kp).*((-1)+(exp(1).^s.kp).^s.Ts).* ...
    s.kp.*((-1)+s.r)+exp(1).^(s.K.*tauGrid).*((exp(1).^s.kp).^s.Ts+(-1).*(exp(1).^s.kp) ...
    .^tauGrid).*s.kp.*((-1)+s.r)+exp(1).^(s.K+s.kp+s.K.*tauGrid).*(s.K.*(s.K+s.kp).*s.r+(exp(1).^s.kp) ...
    .^s.Ts.*(s.kp+s.kp.*s.r.*((-1)+s.K.*((-1)+tauGrid))+s.K.^2.*s.r.*((-1)+tauGrid)))+(-1).*exp( ...
    1).^(s.K+s.K.*tauGrid).*((exp(1).^s.kp).^tauGrid.*(s.kp+s.K.^2.*s.r+((-1)+s.K).*s.kp.*s.r)+(exp( ...
    1).^s.kp).^s.Ts.*s.K.*(s.K+s.kp).*s.r.*((-1)+tauGrid)))+exp(1).^((-1).*s.K.*(1+s.Ts)+( ...
    -1).*s.kp.*((-1)+s.T+s.Ts+tauGrid)).*(exp(1).^s.kp).^((-1).*s.Ts).*(exp(1).^(s.kp.* ...
    s.T)+(-1).*exp(1).^(s.kp.*tauGrid)).*s.kp.*((-1).*exp(1).^((s.K+s.kp).*(1+tauGrid)).*( ...
    exp(1).^s.kp).^s.Ts.*s.kp.*((-1)+s.r)+exp(1).^(s.K+(s.K+s.kp).*tauGrid).*(exp(1).^s.kp) ...
    .^s.Ts.*s.kp.*((-1)+s.r)+exp(1).^((s.K+s.kp).*s.Ts).*((exp(1).^s.kp).^s.Ts+(-1).*( ...
    exp(1).^s.kp).^tauGrid).*s.kp.*((-1)+s.r)+exp(1).^((s.K+s.kp).*(1+s.Ts)).*(exp(1) ...
    .^s.kp).^tauGrid.*((-1).*s.kp+(s.kp+s.K.*(s.K+s.kp)).*s.r)+exp(1).^(s.K+(s.K+s.kp).*s.Ts).*(( ...
    -1).*(exp(1).^s.kp).^tauGrid.*s.K.*(s.K+s.kp).*s.r+(exp(1).^s.kp).^s.Ts.*(s.kp+s.K.^2.*s.r+( ...
    (-1)+s.K).*s.kp.*s.r))+exp(1).^(s.K+s.K.*s.Ts+s.kp.*tauGrid).*(exp(1).^s.kp).^s.Ts.*s.K.*(s.K+ ...
    s.kp).*s.r.*(s.Ts+(-1).*tauGrid)+(-1).*exp(1).^(s.K+s.kp+s.K.*s.Ts+s.kp.*tauGrid).*(exp(1) ...
    .^s.kp).^s.Ts.*s.K.*(s.K+s.kp).*s.r.*(1+s.Ts+(-1).*tauGrid))).*(s.T+(-1).*tauGrid).^(-1);

% intensity-window correlation
autocorr_iw = ((-1)+exp(1).^s.kp).^(-1).*s.K.^(-1).*s.kp.^(-1).*(s.K+s.kp).^(-1).*s.r.*(exp( ...
  1).^((-1).*s.K+(-1).*(s.K+s.kp).*tauGrid).*(exp(1).^s.kp).^((-1).*s.T).*((exp(1) ...
  .^s.kp).^s.T+(-1).*(exp(1).^s.kp).^tauGrid).*((1+(-1).*exp(1).^s.K).*((-1)+exp( ...
  1).^(s.K+s.kp)).*s.kp.*((-1)+s.r)+exp(1).^(s.K+s.K.*tauGrid).*((-1)+exp(1).^s.kp).*s.K.* ...
  (s.K+s.kp).*s.r)+exp(1).^((-1).*s.K.*(1+s.Ts+tauGrid)+(-1).*s.kp.*(s.T+s.Ts+tauGrid)).*(exp(1) ...
  .^(s.kp.*s.T)+(-1).*exp(1).^(s.kp.*tauGrid)).*(((-1)+exp(1).^s.K).*(exp(1).^(s.K+ ...
  s.kp)+(-1).*exp(1).^((s.K+s.kp).*s.Ts)).*s.kp.*((-1)+s.r)+(-1).*exp(1).^(s.K.*( ...
  1+s.Ts+tauGrid)).*(exp(1).^s.kp+(-1).*exp(1).^(s.kp.*s.Ts)).*s.K.*(s.K+s.kp).*s.r)).* ...
  s.Ts.^(-1).*(s.T+(-1).*tauGrid).^(-1);

% window-intensity correlation
autocorr_wi = ((-1)+exp(1).^s.kp).^(-1).*s.K.^(-1).*s.kp.^(-2).*(s.K+s.kp).^(-1).*s.Ts.^(-1) ...
  .*(s.T+(-1).*tauGrid).^(-1).*((-2).*exp(1).^((-1).*s.K+(-1).*s.kp.*(1+s.T+tauGrid)).*( ...
  exp(1).^(s.kp.*(1+s.T))+(-1).*exp(1).^(s.kp.*(1+tauGrid))).*s.r.*(s.kp.^2.*((-1)+ ...
  s.r)+(-1).*exp(1).^(s.K+s.kp).*s.K.*(s.kp+s.K.*s.r)+exp(1).^s.K.*(s.K+s.kp).*(s.kp+s.K.*s.r+ ...
  ((-1)+s.K).*s.kp.*s.r))+exp(1).^((-1).*s.K.*(1+s.Ts)+(-1).*s.kp.*(s.Ts+tauGrid)).*( ...
  exp(1).^s.kp).^((-1).*s.T).*((exp(1).^s.kp).^s.T+(-1).*(exp(1).^s.kp).^tauGrid).* ...
  s.kp.*s.r.*(exp(1).^((s.K+s.kp).*s.Ts).*s.kp.*((-1)+s.r)+(-1).*exp(1).^((s.K+s.kp).* ...
  (1+tauGrid)).*s.kp.*((-1)+s.r)+exp(1).^(2.*s.K+s.kp+(s.K+s.kp).*tauGrid).*s.kp.*((-1)+s.r)+( ...
  -1).*exp(1).^(s.K+s.kp+s.K.*s.Ts+s.kp.*tauGrid).*s.K.*(s.K+s.kp).*s.r+exp(1).^(s.K+(s.K+s.kp).* ...
  s.Ts).*(s.kp+s.K.^2.*s.r+((-1)+s.K).*s.kp.*s.r))+exp(1).^((-1).*s.K+(-1).*(s.K+s.kp).* ...
  tauGrid).*(exp(1).^s.kp).^((-1).*s.T).*((exp(1).^s.kp).^s.T+(-1).*(exp(1).^s.kp) ...
  .^tauGrid).*s.kp.*(((-1)+exp(1).^(s.K+s.kp)).*s.kp.*((-1)+s.r).*s.r+exp(1).^(s.K.*tauGrid).* ...
  s.r.*(exp(1).^s.K.*((-1)+exp(1).^s.kp).*s.K.^2.*s.r.*tauGrid+s.kp.*((-1)+s.r+(-1).* ...
  exp(1).^s.K.*s.K.*s.r.*tauGrid+exp(1).^(s.K+s.kp).*(1+(-1).*s.r+s.K.*s.r.*tauGrid)))));
%

%%% immobile autocorrelation with corrections
imm_autocorr = autocorr_ii - autocorr_iw - autocorr_wi + autocorr_ww;
%%%

%% normalization

% intensity autocorrelation (norm)
autocorr_norm_ii = 2.*exp(1).^((-1).*s.K+(-1).*s.kp.*(1+s.T)).*((-1)+exp(1).^s.kp).^(-1).*(( ...
    -1).*exp(1).^s.kp+exp(1).^(s.kp.*(1+s.T))).*s.K.^(-1).*s.kp.^(-2).*(s.K+s.kp).^( ...
    -1).*s.r.*((-1).*s.kp.^2.*((-1)+s.r)+exp(1).^(s.K+s.kp).*s.K.*(s.kp+s.K.*s.r)+(-1).* ...
    exp(1).^s.K.*(s.K+s.kp).*(s.kp+s.K.*s.r+((-1)+s.K).*s.kp.*s.r)).*s.T.^(-1);
%

% window autocorrelation (norm)
autocorr_norm_ww = ((-1)+exp(1).^s.kp).^(-2).*s.K.^(-1).*s.kp.^(-2).*(s.K+s.kp).^(-1).*s.r.*s.T.^( ...
    -1).*s.Ts.^(-2).*((-2).*exp(1).^((-1).*s.K+(-1).*s.kp.*s.Ts).*(exp(1).^s.kp) ...
    .^((-1).*s.T).*((-1).*exp(1).^s.kp+exp(1).^(s.kp.*(1+s.Ts))).*((-1)+(exp( ...
    1).^s.kp).^s.T).*(s.kp.^2.*((-1)+s.r)+(-1).*exp(1).^(s.K+s.kp).*s.K.*(s.kp+s.K.*s.r)+ ...
    exp(1).^s.K.*(s.K+s.kp).*(s.kp+s.K.*s.r+((-1)+s.K).*s.kp.*s.r))+exp(1).^((-1).*s.K.*( ...
    1+s.Ts)+(-1).*s.kp.*((-1)+s.T+s.Ts)).*(exp(1).^s.kp).^((-1).*s.Ts).*((-1)+exp( ...
    1).^(s.kp.*s.T)).*s.kp.*(exp(1).^s.K.*(exp(1).^s.kp).^s.Ts.*s.kp.*((-1)+s.r)+(-1) ...
    .*exp(1).^(s.K+s.kp).*(exp(1).^s.kp).^s.Ts.*s.kp.*((-1)+s.r)+exp(1).^((s.K+s.kp).* ...
    s.Ts).*((-1)+(exp(1).^s.kp).^s.Ts).*s.kp.*((-1)+s.r)+exp(1).^((s.K+s.kp).*(1+s.Ts) ...
    ).*((-1).*s.kp+(s.kp+s.K.*(s.K+s.kp)).*s.r)+exp(1).^(s.K+(s.K+s.kp).*s.Ts).*((-1).*s.K.* ...
    (s.K+s.kp).*s.r+(exp(1).^s.kp).^s.Ts.*(s.kp+s.K.^2.*s.r+((-1)+s.K).*s.kp.*s.r))+exp(1) ...
    .^(s.K+s.K.*s.Ts).*(exp(1).^s.kp).^s.Ts.*s.K.*(s.K+s.kp).*s.r.*s.Ts+(-1).*exp(1).^(s.K+ ...
    s.kp+s.K.*s.Ts).*(exp(1).^s.kp).^s.Ts.*s.K.*(s.K+s.kp).*s.r.*(1+s.Ts))+(-1).*exp(1).^( ...
    (-1).*s.K.*(1+s.Ts)+(-1).*s.kp.*((-1)+s.T+s.Ts)).*(exp(1).^s.kp).^((-1).*s.Ts).* ...
    ((-1)+exp(1).^(s.kp.*s.T)).*s.kp.*((-1).*exp(1).^s.K.*(exp(1).^s.kp).^s.Ts.* ...
    s.kp.*((-1)+s.r)+exp(1).^(s.K+s.kp).*(exp(1).^s.kp).^s.Ts.*s.kp.*((-1)+s.r)+(-1).* ...
    exp(1).^((s.K+s.kp).*s.Ts).*((-1)+(exp(1).^s.kp).^s.Ts).*s.kp.*((-1)+s.r)+exp(1) ...
    .^((s.K+s.kp).*(1+s.Ts)).*(s.kp+(-1).*(s.kp+s.K.*(s.K+s.kp)).*s.r)+exp(1).^(s.K+(s.K+s.kp) ...
    .*s.Ts).*(s.K.*(s.K+s.kp).*s.r+(-1).*(exp(1).^s.kp).^s.Ts.*(s.kp+s.K.^2.*s.r+((-1)+s.K) ...
    .*s.kp.*s.r))+(-1).*exp(1).^(s.K+s.K.*s.Ts).*(exp(1).^s.kp).^s.Ts.*s.K.*(s.K+s.kp).* ...
    s.r.*s.Ts+exp(1).^(s.K+s.kp+s.K.*s.Ts).*(exp(1).^s.kp).^s.Ts.*s.K.*(s.K+s.kp).*s.r.*(1+s.Ts)));
%

% intensity-window correlation (norm)
autocorr_norm_iw = ((-1)+exp(1).^s.kp).^(-1).*s.K.^(-1).*s.kp.^(-2).*(s.K+s.kp).^(-1).*s.r.*s.T.^( ...
  -1).*s.Ts.^(-1).*(exp(1).^((-1).*s.kp.*(s.T+s.Ts)).*((-1)+exp(1).^(s.kp.*s.T)) ...
  .*s.K.*((-1).*exp(1).^s.kp.*s.kp.*(s.K+s.kp).*s.r+(-1).*exp(1).^(s.kp.*s.Ts).*(2.* ...
  s.K.*s.r+(-2).*exp(1).^s.kp.*(s.kp+s.K.*s.r)+s.kp.*(2+(s.K+s.kp).*s.r)))+8.*exp(1).^(( ...
  -1/2).*s.K.*s.Ts+(-1/2).*s.kp.*((-1)+s.T+s.Ts)).*s.kp.^2.*((-1)+s.r).*cosh((1/2) ...
  .*(s.K+s.kp).*((-1)+s.Ts)).*sinh((1/2).*s.K).*sinh((1/2).*s.kp.*s.T));
%

% window-intensity correlation (norm)
autocorr_norm_wi = exp(1).^((-1).*s.K).*((-1)+exp(1).^s.kp).^(-1).*s.K.^(-1).*s.kp.^(-2).*(s.K+ ...
  s.kp).^(-1).*s.r.*(2.*exp(1).^((-1).*s.kp.*(1+s.T)).*(exp(1).^s.kp+(-1).* ...
  exp(1).^(s.kp.*(1+s.T))).*(s.kp.^2.*((-1)+s.r)+(-1).*exp(1).^(s.K+s.kp).*s.K.*( ...
  s.kp+s.K.*s.r)+exp(1).^s.K.*(s.K+s.kp).*(s.kp+s.K.*s.r+((-1)+s.K).*s.kp.*s.r))+exp(1).^((( ...
  -1).*s.K+(-1).*s.kp).*s.Ts).*(exp(1).^s.kp).^((-1).*s.T).*((-1)+(exp(1).^s.kp) ...
  .^s.T).*s.kp.*(exp(1).^(s.K+s.kp).*(((-1)+exp(1).^s.K).*s.kp.*((-1)+s.r)+(-1).* ...
  exp(1).^(s.K.*s.Ts).*s.K.*(s.K+s.kp).*s.r)+exp(1).^((s.K+s.kp).*s.Ts).*(s.kp.*((-1)+s.r) ...
  +exp(1).^s.K.*(s.kp+s.K.^2.*s.r+((-1)+s.K).*s.kp.*s.r)))).*s.T.^(-1).*s.Ts.^(-1);
%

%%% immobile autocorrelation with corrections (norm)
imm_autocorr_norm = autocorr_norm_ii - autocorr_norm_iw - ...
    autocorr_norm_wi + autocorr_norm_ww;
%%%