function [diff_autocorr,diff_autocorr_norm] = kICSSlideWinDiffBleachFn(s,kSqGrid,tauGrid)

A = s.D.*kSqGrid;

%% numerator

% intensity autocorrelation
autocorr_ii = A.^(-1).*exp(1).^((-1).*A.*(1+tauGrid)+(-1).*s.K.*(1+tauGrid)+(-1).*s.kp.*(1+s.T+tauGrid)) ...
  .*((-1)+exp(1).^s.kp).^(-1).*(exp(1).^(s.kp.*(1+s.T))+(-1).*exp(1).^( ...
  s.kp.*(1+tauGrid))).*(A+s.K).^(-1).*(A+s.kp).^(-1).*(A+s.K+s.kp).^(-1).*s.r.*(A.*(( ...
  -1)+exp(1).^(A+s.K)).*((-1)+exp(1).^(A+s.K+s.kp)).*(A+s.kp).*((-1)+s.r)+(-1) ...
  .*exp(1).^(s.K+s.K.*tauGrid).*((-1)+exp(1).^A).*((-1)+exp(1).^(A+s.kp)).*(A+s.K) ...
  .*(A+s.K+s.kp).*s.r).*((-1).*s.T+tauGrid).^(-1);
%

% window autocorrelation
autocorr_ww = (-1).*A.^(-1).*((-1)+exp(1).^s.kp).^(-2).*(A+s.K).^(-1).*s.kp.^(-1).*(A+ ...
  s.kp).^(-1).*(A+s.K+s.kp).^(-1).*s.r.*((-1).*exp(1).^((-1).*A.*(1+tauGrid)+(-1) ...
  .*s.K.*(1+tauGrid)+(-1).*s.kp.*(s.Ts+2.*tauGrid)).*(exp(1).^s.kp).^((-1).*s.T).*(exp(1) ...
  .^(s.kp.*(1+tauGrid))+(-1).*exp(1).^(s.kp.*(1+s.Ts+tauGrid))).*((exp(1).^s.kp).^s.T+(-1) ...
  .*(exp(1).^s.kp).^tauGrid).*s.kp.*(A.*((-1)+exp(1).^(A+s.K)).*((-1)+exp(1).^( ...
  A+s.K+s.kp)).*(A+s.kp).*((-1)+s.r)+(-1).*exp(1).^(s.K+s.K.*tauGrid).*((-1)+exp(1) ...
  .^A).*((-1)+exp(1).^(A+s.kp)).*(A+s.K).*(A+s.K+s.kp).*s.r)+exp(1).^((-1).* ...
  A.*(1+s.Ts+tauGrid)).*s.kp.*((-1).*A.*exp(1).^((-1).*s.kp.*((-1)+s.Ts+tauGrid)+(-1).* ...
  s.K.*(1+s.Ts+tauGrid)).*(exp(1).^s.kp).^((-1).*s.T).*(exp(1).^(A+s.K)+(-1).*exp(1) ...
  .^(A+s.K+s.kp)+(-1).*exp(1).^((A+s.K).*s.Ts)+exp(1).^((A+s.K+s.kp).*s.Ts)+exp(1) ...
  .^(A+s.K+s.kp+A.*s.Ts+s.K.*s.Ts)+(-1).*exp(1).^(A+s.K+A.*s.Ts+s.K.*s.Ts+s.kp.*s.Ts)).*(( ...
  exp(1).^s.kp).^s.T+(-1).*(exp(1).^s.kp).^tauGrid).*(A+s.kp).*((-1)+s.r)+exp(1).^(( ...
  -1).*s.kp.*((-1)+s.T+s.Ts+tauGrid)).*(exp(1).^A+(-1).*exp(1).^(A+s.kp)+(-1).* ...
  exp(1).^(A.*s.Ts)+exp(1).^((A+s.kp).*s.Ts)+exp(1).^(A+s.kp+A.*s.Ts)+(-1).* ...
  exp(1).^(A+A.*s.Ts+s.kp.*s.Ts)).*(exp(1).^(s.kp.*s.T)+(-1).*exp(1).^(s.kp.*tauGrid)) ...
  .*(A+s.K).*(A+s.K+s.kp).*s.r)+exp(1).^((-1).*A+(-1).*s.kp.*((-1)+s.T+2.*s.Ts+tauGrid)) ...
  .*(exp(1).^(s.kp.*(s.T+s.Ts))+(-1).*exp(1).^(s.kp.*(s.Ts+tauGrid))).*s.kp.*(A.*exp( ...
  1).^((-1).*s.K+(-1).*(A+s.K).*s.Ts).*((-1).*exp(1).^((A+s.K+s.kp).*s.Ts)+exp( ...
  1).^(A+s.K+(A+s.K+s.kp).*s.Ts)+exp(1).^((A+s.K+s.kp).*(1+tauGrid))+exp(1).^((A+s.K).* ...
  s.Ts+s.kp.*tauGrid)+(-1).*exp(1).^(A+s.K+s.kp+(A+s.K).*s.Ts+s.kp.*tauGrid)+(-1).*exp(1).^(A+ ...
  s.K+(A+s.K+s.kp).*tauGrid)).*(A+s.kp).*((-1)+s.r)+exp(1).^((-1).*A.*s.Ts).*(exp(1) ...
  .^((A+s.kp).*s.Ts)+(-1).*exp(1).^(A+(A+s.kp).*s.Ts)+(-1).*exp(1).^((A+s.kp) ...
  .*(1+tauGrid))+(-1).*exp(1).^(A.*s.Ts+s.kp.*tauGrid)+exp(1).^(A+s.kp+A.*s.Ts+s.kp.*tauGrid)+ ...
  exp(1).^(A+(A+s.kp).*tauGrid)).*(A+s.K).*(A+s.K+s.kp).*s.r)+exp(1).^((-1).*s.kp+(-1) ...
  .*A.*(1+tauGrid)).*s.kp.*(A.*exp(1).^((-1).*s.K.*(1+tauGrid)+(-1).*s.kp.*((-2)+s.T+s.Ts+ ...
  tauGrid)).*(exp(1).^(s.kp.*s.T)+(-1).*exp(1).^(s.kp.*tauGrid)).*(exp(1).^(s.kp.*s.Ts).*( ...
  (-1)+exp(1).^(A+s.K+s.kp)).*(exp(1).^(A+s.K)+(-1).*exp(1).^((A+s.K).*tauGrid))+( ...
  -1).*((-1)+exp(1).^(A+s.K)).*(exp(1).^(A+s.K+s.kp)+(-1).*exp(1).^((A+s.K+ ...
  s.kp).*tauGrid))).*(A+s.kp).*(1+(-1).*s.r)+exp(1).^((-1).*s.kp.*((-2)+s.Ts+tauGrid)).*( ...
  exp(1).^s.kp).^((-1).*s.T).*((exp(1).^s.kp).^s.T+(-1).*(exp(1).^s.kp).^tauGrid).*( ...
  exp(1).^(s.kp.*s.Ts).*((-1)+exp(1).^(A+s.kp)).*(exp(1).^A+(-1).*exp(1) ...
  .^(A.*tauGrid))+(-1).*((-1)+exp(1).^A).*(exp(1).^(A+s.kp)+(-1).*exp(1).^(( ...
  A+s.kp).*tauGrid))).*(A+s.K).*(A+s.K+s.kp).*s.r)+(-2).*exp(1).^((-1).*A+(-1).*s.K+( ...
  -1).*s.kp.*((-1)+s.T+s.Ts+tauGrid)).*(exp(1).^(s.kp.*s.T)+(-1).*exp(1).^(s.kp.*tauGrid)).* ...
  (exp(1).^(s.kp.*s.Ts)+(-1).*exp(1).^(s.kp.*tauGrid)).*(A.^3.*exp(1).^(A+s.K).*(( ...
  -1)+exp(1).^s.kp)+(-1).*exp(1).^s.K.*((-1)+exp(1).^A).*s.K.*s.kp.*(s.K+s.kp).* ...
  s.r+A.^2.*(s.kp+(-1).*s.kp.*s.r+exp(1).^s.K.*s.kp.*s.r+exp(1).^(A+s.K+s.kp).*(s.K+s.kp+ ...
  s.K.*s.r)+(-1).*exp(1).^(A+s.K).*(s.K+2.*s.kp+s.K.*s.r))+A.*((-1).*s.kp.^2.*((-1)+ ...
  s.r)+exp(1).^s.K.*s.kp.*(2.*s.K+s.kp).*s.r+exp(1).^(A+s.K+s.kp).*s.K.*(s.kp+s.K.*s.r)+(-1) ...
  .*exp(1).^(A+s.K).*(s.kp.*(s.K+s.kp)+s.K.*(s.K+2.*s.kp).*s.r)))).*s.Ts.^(-2).*(s.T+( ...
  -1).*tauGrid).^(-1);

% intensity-window correlation
autocorr_iw = (-1).*A.^(-1).*((-1)+exp(1).^s.kp).^(-1).*(A+s.K).^(-1).*(A+s.kp).^(-1) ...
  .*(A+s.K+s.kp).^(-1).*s.r.*(exp(1).^((-1).*A+(-1).*s.kp.*(s.T+s.Ts)).*(1+(-1) ...
  .*exp(1).^(s.kp.*(s.T+(-1).*tauGrid))).*(A.*exp(1).^((-1).*s.K+(-1).*(A+s.K).*( ...
  s.Ts+tauGrid)).*((-1)+exp(1).^(A+s.K)).*(exp(1).^(A+s.K+s.kp)+(-1).*exp(1).^((A+ ...
  s.K+s.kp).*s.Ts)).*(A+s.kp).*((-1)+s.r)+(-1).*exp(1).^((-1).*A.*(s.Ts+tauGrid)).*(( ...
  -1)+exp(1).^A).*(exp(1).^(A+s.kp)+(-1).*exp(1).^((A+s.kp).*s.Ts)).*(A+s.K) ...
  .*(A+s.K+s.kp).*s.r)+(-1).*exp(1).^((-1).*A.*(1+tauGrid)+(-1).*s.K.*(1+tauGrid)+(-1).* ...
  s.kp.*(1+s.T+tauGrid)).*(exp(1).^(s.kp+s.kp.*s.T)+(-1).*exp(1).^(s.kp.*(1+tauGrid))).*(( ...
  exp(1).^(s.K.*(1+tauGrid))+(-1).*exp(1).^(A+s.K+s.K.*tauGrid)+exp(1).^(A+s.K+s.kp+s.K.*tauGrid) ...
  .*((-1)+exp(1).^A)).*s.K.*(s.K+s.kp).*s.r+A.*exp(1).^(s.K.*(1+tauGrid)).*(2.*((-1) ...
  +exp(1).^A).*((-1)+exp(1).^(A+s.kp)).*s.K+s.kp).*s.r+A.*s.kp.*((1+(-1).*exp( ...
  1).^(A+s.K)).*((-1)+exp(1).^(A+s.K+s.kp)).*((-1)+s.r)+exp(1).^(A+s.K+s.K.*tauGrid).* ...
  ((-1)+exp(1).^s.kp.*((-1)+exp(1).^A)).*s.r)+(-1).*A.^2.*((-1)+s.r+(-1).* ...
  exp(1).^(s.K.*(1+tauGrid)).*s.r+exp(1).^(A+s.K).*(((-1)+(-1).*exp(1).^s.kp+exp( ...
  1).^(A+s.K+s.kp)).*((-1)+s.r)+(-1).*exp(1).^(s.K.*tauGrid).*((-1)+exp(1).^s.kp.*(( ...
  -1)+exp(1).^A)).*s.r)))).*s.Ts.^(-1).*(s.T+(-1).*tauGrid).^(-1);

% window-intensity correlation
autocorr_wi = A.^(-1).*((-1)+exp(1).^s.kp).^(-1).*(A+s.K).^(-1).*(A+s.kp).^(-1).*(A+s.K+ ...
  s.kp).^(-1).*s.r.*(exp(1).^((-1).*A.*(1+s.Ts)+(-1).*s.K.*(1+s.Ts)+(-1).*s.kp.* ...
  (s.T+s.Ts+tauGrid)).*(exp(1).^(s.kp.*s.T)+(-1).*exp(1).^(s.kp.*tauGrid)).*(exp(1).^s.K.*(( ...
  -1)+exp(1).^A).*(exp(1).^((A+s.K+s.kp).*s.Ts)+(-1).*exp(1).^(s.K.*s.Ts+(A+ ...
  s.kp).*(1+tauGrid))).*s.K.*(s.K+s.kp).*s.r+A.^2.*(exp(1).^(A+s.K+(A+s.K+s.kp).*s.Ts)+exp( ...
  1).^((A+s.K+s.kp).*s.Ts).*((-1)+s.r)+(-1).*exp(1).^((A+s.K+s.kp).*(1+tauGrid)).*(( ...
  -1)+s.r)+exp(1).^(2.*A+2.*s.K+s.kp+(A+s.K+s.kp).*tauGrid).*((-1)+s.r)+(-1).*exp(1) ...
  .^(s.K+(A+s.K+s.kp).*s.Ts).*s.r+exp(1).^(A+s.K+s.kp+s.K.*s.Ts+(A+s.kp).*tauGrid).*s.r+(-1).* ...
  exp(1).^(s.K+s.kp+s.K.*s.Ts+s.kp.*tauGrid+A.*(2+tauGrid)).*s.r)+A.*(exp(1).^((A+s.K+s.kp).*s.Ts) ...
  .*s.kp.*((-1)+s.r)+(-1).*exp(1).^((A+s.K+s.kp).*(1+tauGrid)).*s.kp.*((-1)+s.r)+exp( ...
  1).^(2.*A+2.*s.K+s.kp+(A+s.K+s.kp).*tauGrid).*s.kp.*((-1)+s.r)+(-1).*exp(1).^(s.K+(A+ ...
  s.K+s.kp).*s.Ts).*(2.*s.K+s.kp).*s.r+exp(1).^(A+s.K+s.kp+s.K.*s.Ts+(A+s.kp).*tauGrid).*(2.*s.K+ ...
  s.kp).*s.r+(-1).*exp(1).^(s.K+s.kp+s.K.*s.Ts+s.kp.*tauGrid+A.*(2+tauGrid)).*(2.*s.K+s.kp).*s.r+ ...
  exp(1).^(A+s.K+(A+s.K+s.kp).*s.Ts).*(s.kp+2.*s.K.*s.r)))+exp(1).^((-1).*A.*(3+tauGrid) ...
  +(-1).*s.K.*(3+tauGrid)+(-1).*s.kp.*(1+s.T+tauGrid)).*(exp(1).^(s.kp.*(1+s.T))+(-1).* ...
  exp(1).^(s.kp.*(1+tauGrid))).*(exp(1).^(2.*A+s.K.*(3+tauGrid)).*((-1)+exp(1).^(A+ ...
  s.kp)).*((-1)+exp(1).^(A.*tauGrid)).*s.K.*(s.K+s.kp).*s.r+A.^2.*exp(1).^(2.*(A+s.K)) ...
  .*(1+exp(1).^(A+s.K+s.kp+A.*tauGrid+s.K.*tauGrid)+exp(1).^(A+s.K+s.kp).*((-1)+s.r)+exp(1) ...
  .^((A+s.K).*tauGrid).*((-1)+s.r)+(-1).*s.r+exp(1).^(s.K+s.K.*tauGrid).*s.r+(-1).*exp(1).^( ...
  A+s.K+s.kp+s.K.*tauGrid).*s.r+(-1).*exp(1).^(s.K+A.*tauGrid+s.K.*tauGrid).*s.r)+A.*((-1).*exp(1) ...
  .^(2.*(A+s.K)).*s.kp.*((-1)+s.r)+exp(1).^(3.*A+3.*s.K+s.kp).*s.kp.*((-1)+s.r)+ ...
  exp(1).^((A+s.K).*(2+tauGrid)).*s.kp.*((-1)+s.r)+exp(1).^(2.*A+s.K.*(3+tauGrid)).*(2.* ...
  s.K+s.kp).*s.r+(-1).*exp(1).^(3.*A+s.kp+s.K.*(3+tauGrid)).*(2.*s.K+s.kp).*s.r+(-1).*exp( ...
  1).^(A.*(2+tauGrid)+s.K.*(3+tauGrid)).*(2.*s.K+s.kp).*s.r+exp(1).^(s.kp+A.*(3+tauGrid)+s.K.*(3+ ...
  tauGrid)).*(s.kp+2.*s.K.*s.r)))+2.*exp(1).^((-1).*A+(-1).*s.K+(-1).*s.kp.*(s.T+tauGrid)).* ...
  (exp(1).^(s.kp.*s.T)+(-1).*exp(1).^(s.kp.*tauGrid)).*s.kp.^(-1).*(A.^3.*exp(1) ...
  .^(A+s.K).*((-1)+exp(1).^s.kp)+(-1).*exp(1).^s.K.*((-1)+exp(1).^A).*s.K.* ...
  s.kp.*(s.K+s.kp).*s.r+A.^2.*(s.kp+(-1).*s.kp.*s.r+exp(1).^s.K.*s.kp.*s.r+exp(1).^(A+s.K+ ...
  s.kp).*(s.K+s.kp+s.K.*s.r)+(-1).*exp(1).^(A+s.K).*(s.K+2.*s.kp+s.K.*s.r))+A.*((-1).* ...
  s.kp.^2.*((-1)+s.r)+exp(1).^s.K.*s.kp.*(2.*s.K+s.kp).*s.r+exp(1).^(A+s.K+s.kp).*s.K.*( ...
  s.kp+s.K.*s.r)+(-1).*exp(1).^(A+s.K).*(s.kp.*(s.K+s.kp)+s.K.*(s.K+2.*s.kp).*s.r)))).* ...
  s.Ts.^(-1).*(s.T+(-1).*tauGrid).^(-1);
%

%%% immobile autocorrelation with corrections
diff_autocorr = autocorr_ii + autocorr_ww - autocorr_iw - autocorr_wi;
%%%

%% normalization

% intensity autocorrelation (norm)
autocorr_norm_ii = 2.*A.^(-1).*exp(1).^((-1).*A+(-1).*s.K+(-1).*s.kp.*s.T).*((-1)+exp(1) ...
  .^s.kp).^(-1).*((-1)+exp(1).^(s.kp.*s.T)).*(A+s.K).^(-1).*s.kp.^(-1).*(A+s.kp) ...
  .^(-1).*(A+s.K+s.kp).^(-1).*s.r.*(A.^3.*exp(1).^(A+s.K).*((-1)+exp(1).^s.kp) ...
  +(-1).*exp(1).^s.K.*((-1)+exp(1).^A).*s.K.*s.kp.*(s.K+s.kp).*s.r+A.^2.*(s.kp+( ...
  -1).*s.kp.*s.r+exp(1).^s.K.*s.kp.*s.r+exp(1).^(A+s.K+s.kp).*(s.K+s.kp+s.K.*s.r)+(-1).* ...
  exp(1).^(A+s.K).*(s.K+2.*s.kp+s.K.*s.r))+A.*((-1).*s.kp.^2.*((-1)+s.r)+exp(1) ...
  .^s.K.*s.kp.*(2.*s.K+s.kp).*s.r+exp(1).^(A+s.K+s.kp).*s.K.*(s.kp+s.K.*s.r)+(-1).*exp(1) ...
  .^(A+s.K).*(s.kp.*(s.K+s.kp)+s.K.*(s.K+2.*s.kp).*s.r))).*s.T.^(-1);
%

% window autocorrelation (norm)
autocorr_norm_ww = A.^(-1).*((-1)+exp(1).^s.kp).^(-2).*(A+s.K).^(-1).*s.kp.^(-1).*(A+s.kp).^( ...
  -1).*(A+s.K+s.kp).^(-1).*s.r.*(exp(1).^((-1).*A.*(1+s.Ts)).*s.kp.*(A.*exp(1) ...
  .^(s.kp+(-1).*s.kp.*s.Ts+(-1).*s.K.*(1+s.Ts)).*(exp(1).^s.kp).^((-1).*s.T).*( ...
  exp(1).^(A+s.K)+(-1).*exp(1).^(A+s.K+s.kp)+(-1).*exp(1).^((A+s.K).*s.Ts)+ ...
  exp(1).^((A+s.K+s.kp).*s.Ts)+exp(1).^(A+s.K+s.kp+A.*s.Ts+s.K.*s.Ts)+(-1).*exp(1) ...
  .^(A+s.K+A.*s.Ts+s.K.*s.Ts+s.kp.*s.Ts)).*((-1)+(exp(1).^s.kp).^s.T).*(A+s.kp).*((-1) ...
  +s.r)+exp(1).^((-1).*s.kp.*((-1)+s.T+s.Ts)).*((-1)+exp(1).^(s.kp.*s.T)).*((-1) ...
  .*exp(1).^A+exp(1).^(A+s.kp)+exp(1).^(A.*s.Ts)+(-1).*exp(1).^((A+s.kp).* ...
  s.Ts)+(-1).*exp(1).^(A+s.kp+A.*s.Ts)+exp(1).^(A+A.*s.Ts+s.kp.*s.Ts)).*(A+s.K).*( ...
  A+s.K+s.kp).*s.r)+exp(1).^((-1).*A+(-1).*s.kp.*((-1)+s.T+2.*s.Ts)).*(exp(1).^( ...
  s.kp.*s.Ts)+(-1).*exp(1).^(s.kp.*(s.T+s.Ts))).*s.kp.*((-1).*A.*exp(1).^((-1).* ...
  s.K+(-1).*(A+s.K).*s.Ts).*(exp(1).^(A+s.K)+(-1).*exp(1).^(A+s.K+s.kp)+(-1).* ...
  exp(1).^((A+s.K).*s.Ts)+exp(1).^((A+s.K+s.kp).*s.Ts)+exp(1).^(A+s.K+s.kp+(A+s.K).* ...
  s.Ts)+(-1).*exp(1).^(A+s.K+(A+s.K+s.kp).*s.Ts)).*(A+s.kp).*((-1)+s.r)+exp(1).^(( ...
  -1).*A.*s.Ts).*(exp(1).^A+(-1).*exp(1).^(A+s.kp)+(-1).*exp(1).^(A.*s.Ts) ...
  +exp(1).^((A+s.kp).*s.Ts)+exp(1).^(A+s.kp+A.*s.Ts)+(-1).*exp(1).^(A+(A+s.kp) ...
  .*s.Ts)).*(A+s.K).*(A+s.K+s.kp).*s.r)+2.*exp(1).^((-1).*A+(-1).*s.K+(-1).*s.kp.* ...
  ((-1)+s.T+s.Ts)).*((-1)+exp(1).^(s.kp.*s.T)).*((-1)+exp(1).^(s.kp.*s.Ts)).*( ...
  A.^3.*exp(1).^(A+s.K).*((-1)+exp(1).^s.kp)+(-1).*exp(1).^s.K.*((-1)+exp( ...
  1).^A).*s.K.*s.kp.*(s.K+s.kp).*s.r+A.^2.*(s.kp+(-1).*s.kp.*s.r+exp(1).^s.K.*s.kp.*s.r+ ...
  exp(1).^(A+s.K+s.kp).*(s.K+s.kp+s.K.*s.r)+(-1).*exp(1).^(A+s.K).*(s.K+2.*s.kp+s.K.*s.r)) ...
  +A.*((-1).*s.kp.^2.*((-1)+s.r)+exp(1).^s.K.*s.kp.*(2.*s.K+s.kp).*s.r+exp(1).^(A+ ...
  s.K+s.kp).*s.K.*(s.kp+s.K.*s.r)+(-1).*exp(1).^(A+s.K).*(s.K.*s.kp+s.kp.^2+s.K.^2.*s.r+2.* ...
  s.K.*s.kp.*s.r)))).*s.T.^(-1).*s.Ts.^(-2);
%

% intensity-window correlation (norm)
autocorr_norm_iw = (-1).*A.^(-1).*exp(1).^((-1).*A).*((-1)+exp(1).^s.kp).^(-1).*(1+(-1) ...
  .*exp(1).^(s.kp.*s.T)).*(A+s.K).^(-1).*s.kp.^(-1).*(A+s.kp).^(-1).*(A+s.K+s.kp) ...
  .^(-1).*s.r.*(exp(1).^((-1).*s.kp.*(s.T+s.Ts)).*s.kp.*(A.*exp(1).^((-1).*s.K+( ...
  -1).*(A+s.K).*s.Ts).*((-1)+exp(1).^(A+s.K)).*(exp(1).^(A+s.K+s.kp)+(-1).* ...
  exp(1).^((A+s.K+s.kp).*s.Ts)).*(A+s.kp).*((-1)+s.r)+(-1).*exp(1).^((-1).*A.* ...
  s.Ts).*((-1)+exp(1).^A).*(exp(1).^(A+s.kp)+(-1).*exp(1).^((A+s.kp).*s.Ts)) ...
  .*(A+s.K).*(A+s.K+s.kp).*s.r)+2.*exp(1).^((-1).*s.K+(-1).*s.kp.*s.T).*(A.^3.* ...
  exp(1).^(A+s.K).*((-1)+exp(1).^s.kp)+(-1).*exp(1).^s.K.*((-1)+exp(1).^A) ...
  .*s.K.*s.kp.*(s.K+s.kp).*s.r+A.^2.*(s.kp+(-1).*s.kp.*s.r+exp(1).^s.K.*s.kp.*s.r+exp(1) ...
  .^(A+s.K+s.kp).*(s.K+s.kp+s.K.*s.r)+(-1).*exp(1).^(A+s.K).*(s.K+2.*s.kp+s.K.*s.r))+A.*(( ...
  -1).*s.kp.^2.*((-1)+s.r)+exp(1).^s.K.*s.kp.*(2.*s.K+s.kp).*s.r+exp(1).^(A+s.K+s.kp) ...
  .*s.K.*(s.kp+s.K.*s.r)+(-1).*exp(1).^(A+s.K).*(s.kp.*(s.K+s.kp)+s.K.*(s.K+2.*s.kp).*s.r))) ...
  ).*s.T.^(-1).*s.Ts.^(-1);
%

% window-intensity correlation (norm)
autocorr_norm_wi = A.^(-1).*((-1)+exp(1).^s.kp).^(-1).*((-1)+exp(1).^(s.kp.*s.T)).*(A+s.K).^( ...
  -1).*(A+s.kp).^(-1).*(A+s.K+s.kp).^(-1).*s.r.*(2.*exp(1).^((-1).*A+(-1).* ...
  s.K+(-1).*s.kp.*s.T).*s.kp.^(-1).*(A.^3.*exp(1).^(A+s.K).*((-1)+exp(1).^s.kp)+ ...
  (-1).*exp(1).^s.K.*((-1)+exp(1).^A).*s.K.*s.kp.*(s.K+s.kp).*s.r+A.^2.*(s.kp+(-1) ...
  .*s.kp.*s.r+exp(1).^s.K.*s.kp.*s.r+exp(1).^(A+s.K+s.kp).*(s.K+s.kp+s.K.*s.r)+(-1).*exp( ...
  1).^(A+s.K).*(s.K+2.*s.kp+s.K.*s.r))+A.*((-1).*s.kp.^2.*((-1)+s.r)+exp(1).^s.K.* ...
  s.kp.*(2.*s.K+s.kp).*s.r+exp(1).^(A+s.K+s.kp).*s.K.*(s.kp+s.K.*s.r)+(-1).*exp(1).^(A+ ...
  s.K).*(s.kp.*(s.K+s.kp)+s.K.*(s.K+2.*s.kp).*s.r)))+exp(1).^((-1).*A.*(1+s.Ts)+(-1).* ...
  s.K.*(1+s.Ts)+(-1).*s.kp.*(s.T+s.Ts)).*((-1).*exp(1).^s.K.*((-1)+exp(1).^A).*( ...
  (-1).*exp(1).^((A+s.K+s.kp).*s.Ts)+exp(1).^(A+s.kp+s.K.*s.Ts)).*s.K.*(s.K+s.kp).*s.r+ ...
  A.*exp(1).^(A+s.K+s.kp).*(((-1)+exp(1).^(A+s.K)).*s.kp.*((-1)+s.r)+(-1).* ...
  exp(1).^(s.K.*s.Ts).*((-1)+exp(1).^A).*(2.*s.K+s.kp).*s.r)+A.^2.*(exp(1).^(( ...
  A+s.K+s.kp).*s.Ts).*((-1)+exp(1).^(A+s.K)+s.r+(-1).*exp(1).^s.K.*s.r)+exp(1).^( ...
  A+s.K+s.kp).*(((-1)+exp(1).^(A+s.K)).*((-1)+s.r)+(-1).*exp(1).^(s.K.*s.Ts).*(( ...
  -1)+exp(1).^A).*s.r))+A.*exp(1).^((A+s.K+s.kp).*s.Ts).*(s.kp.*((-1)+s.r)+exp( ...
  1).^s.K.*(((-2).*s.K+(-1).*s.kp).*s.r+exp(1).^A.*(s.kp+2.*s.K.*s.r))))).*s.T.^(-1) ...
  .*s.Ts.^(-1);
%

%%% immobile autocorrelation with corrections (norm)
diff_autocorr_norm = autocorr_norm_ii + autocorr_norm_ww - autocorr_norm_iw - autocorr_norm_wi;
%%%