#!/bin/bash

Q_TYPE="condor" # input either "condor" or "torque"

########### INPUT VARIABLES ###################

# These variables don't need to be updated in either analysisInput.txt, or submitMatlabJob

RUNTAG="manymins"																	# 
RUNCLASS="high-noise" 														# organizational subdirectory
CODECLASS="SOFI-Project" 													# project name
CODEPATH="/media/3TB-GPU-Drive/simon.sehayek/Simon/Code" 					# folder containing all codes (recursive)
BASEDIR="/media/3TB-GPU-Drive/simon.sehayek/Simon/runs/${CODECLASS}/main" 	# folder for storing the runs
SAVESIMDIR="${BASEDIR}/SimulationData"										# folder for storing simulations

CREATESIM=1				# create simulations logical
FITSIM=1 				# compare theory to simulations logical
LOADREP_ARR=1 			# simulation repetition numbers to load (only relevant if FITSIM=1 & CREATESIM=0)
						# bash syntax ({start..end})
					
###############################################

if [[ ${CREATESIM} -eq 1 ]] # $LOADREP_ARR is not relevant if creating another simulation,
                            # in this case $LOADREP_ARR is set to empty MATLAB array
then 
	unset LOADREP_ARR
	LOADREP_ARR="[]"   
fi

NREPS=${#LOADREP_ARR[@]} # number of elements in ${LOADREP_ARR}
for (( i=0; i<${NREPS}; i++ ));
do
	#rm QSub*
	#rm Execute*
	#rm program_output.txt
	
	LOADREP=${LOADREP_ARR[$i]}

	NEWDIR="${BASEDIR}/queued-jobs/" # job temp directory


	# unique job names
	UUID=$(uuidgen)
	NEWDIR="${NEWDIR}${UUID}"
			
	mkdir -p "${NEWDIR}"

	cd "${BASEDIR}"

	sed -i '/runTag/c\'\'"${RUNTAG}\' |"' runTag' analysisInput.txt
	sed -i '/runClass/c\'\'"${RUNCLASS}\' |"' runClass' analysisInput.txt
	sed -i '/runDir/c\'\'"${NEWDIR}\' |"' runDir' analysisInput.txt
	sed -i '/baseDir/c\'\'"${BASEDIR}\' |"' baseDir' analysisInput.txt
	sed -i '/saveSimDir/c\'\'"${SAVESIMDIR}\' |"' saveSimDir' analysisInput.txt

	sed -i '/createSim/c\'"${CREATESIM} |"' createSim' analysisInput.txt
	sed -i '/fitSim/c\'"${FITSIM} |"' fitSim' analysisInput.txt
	sed -i '/loadRep/c\'"${LOADREP} |"' loadRep' analysisInput.txt

	sed -i '/NEWDIR=/c\NEWDIR='\""${NEWDIR}"\"'' submitMatlabJob
	sed -i '/CODEPATH=/c\CODEPATH='\""${CODEPATH}"\"'' submitMatlabJob
	sed -i '/CODECLASS=/c\CODECLASS='\""${CODECLASS}"\"'' submitMatlabJob
	sed -i '/RUNTAG=/c\RUNTAG='\""${RUNTAG}"\"'' submitMatlabJob
	
	#sed -i '/initialdir=/c\initialdir='"${NEWDIR}"'' condor_script

	cd "${CODEPATH}/GeneralUtilities"
	#ln -s ${CODEPATH}/GeneralUtilities/getAnalysisInput.m ${NEWDIR}
	cp getAnalysisInput.m{,.tmp}
	mv getAnalysisInput.m "${NEWDIR}"
	cp getAnalysisInput{.m.tmp,.m}
	rm getAnalysisInput.m.tmp

	cd "${BASEDIR}"

	cp analysisInput.txt{,.mv}
	mv analysisInput.txt.mv "${NEWDIR}"

	cp submitMatlabJob{,.mv}
	mv submitMatlabJob.mv "${NEWDIR}"
	
	if [[ "$Q_TYPE" == "condor" ]]
	then 
		cp condor_script{,.mv}
		mv condor_script.mv "${NEWDIR}"		
	fi

	cd "${NEWDIR}"

	### SUBMIT JOB TO QUEUE

	if [[ "$Q_TYPE" == "torque" ]]
	then	
		qsub -V \
			-o outputfile \
			-e errorfile \
			-l h_rt=24:00:00 \
			-cwd \
			-N "simon_job" \
			-m e \
			-M "${USER}@gmail.com" \
			"submitMatlabJob.mv"
			
		rm submitMatlabJob.mv
	else 
		condor_submit condor_script.mv
	fi
done